//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecio
    {
        public ListaPrecio()
        {
            this.GrupoXListaPrecio = new HashSet<GrupoXListaPrecio>();
            this.ListaPrecioXLProd = new HashSet<ListaPrecioXLProd>();
        }
    
        public int idListaPrecio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PorcentajePrecio { get; set; }
        public Nullable<int> CantidadProductos { get; set; }
        public string ProductoDistinto { get; set; }
    
        public virtual ICollection<GrupoXListaPrecio> GrupoXListaPrecio { get; set; }
        public virtual ICollection<ListaPrecioXLProd> ListaPrecioXLProd { get; set; }
    }
}
