//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CompraDetalle = new HashSet<CompraDetalle>();
            this.GrupoXProducto = new HashSet<GrupoXProducto>();
            this.ListaProducto = new HashSet<ListaProducto>();
            this.Stock = new HashSet<Stock>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int idProveedor { get; set; }
        public string CodigoBarras { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        [JsonIgnore]
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
        [JsonIgnore]
        public virtual ICollection<GrupoXProducto> GrupoXProducto { get; set; }
        [JsonIgnore]
        public virtual ICollection<ListaProducto> ListaProducto { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
        [JsonIgnore]
        public virtual ProductoPrecio ProductoPrecio { get; set; }
        [JsonIgnore]
        public virtual ICollection<Stock> Stock { get; set; }
        [JsonIgnore]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }

    }
}
