//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Compra = new HashSet<Compra>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int idProveedor { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
